version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  service:
    build: .
