services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DATABASE: 'teste-backend-brainny'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
